### ISSUE TITLE
sbt run fails with ClassNotFoundException

### ISSUE THREAD

**Issue by decafbad** [UdashFramework/udash.g8#15]
It's me again. After `compile` and `compileStatics`
```
sbt:my-udash-application> run
[info] Packaging (*)/my-udash-application/target/scala-2.12/my-udash-application_2.12-0.1.0-SNAPSHOT.jar ...
[info] Done packaging.
[info] Running io.company.app.backend.Launcher 
[error] (run-main-1) java.lang.ClassNotFoundException: io.company.app.backend.Launcher
[error] java.lang.ClassNotFoundException: io.company.app.backend.Launcher
[error] 	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] Nonzero exit code: 1
[error] (Compile / run) Nonzero exit code: 1
[error] Total time: 2 s, completed Sep 2, 2019 3:36:30 PM
```
That jar is empty, only manifest file. There were also eviction warnings.

**Comment by ddworak** [comment]
@decafbad do you have the same issue when you run `backend/run`?

**Comment by decafbad** [comment]
That one works.

**Comment by ddworak** [comment]
I'll try to add an alias to the root project to reflect the current build structure or update the docs accordingly.
